
fragment basicManufacturerFields on manufacturer {
    id # Int
    name # String
    url # String
    vendor_id # Int
    icon_url # String
}

fragment objectManufacturerFields on manufacturer {
	vendor {
		...basicVendorFields
	}
    manufacturer_items {
        ...basicManufacturerItemFields
    }
    # manufacturer_items_aggregate {
    #   aggregate {
    #     count
    #   }
    # }
}

fragment basicManufacturerItemFields on manufacturer_item {
      id
      item_id
      manufacturer_id
      manufacturer_product_id
      manufacturer_product_name
      manufacturer_product_series
      product_url
      description
}
fragment objectManufacturerItemFields on manufacturer_item {
      manufacturer {
          ...basicManufacturerFields
      }
}

query GetManufacturers {
	manufacturer(order_by: { id: asc }) {
		...basicManufacturerFields
	}
}


query GetManufacturer($id: Int!) {
	manufacturer: manufacturer_by_pk(id: $id) {
		...basicManufacturerFields
		...objectManufacturerFields
	}
}


query SearchManufacturers($search_string: String) {
	manufacturer(order_by: { id: asc }, where: { name: { _ilike: $search_string }}) {
        ...basicManufacturerFields
    }
}


mutation InsertManufacturer (
$name: String!
$url: String
$vendor_id: Int
) {
    manufacturer: insert_manufacturer_one(object: {
        name: $name
        url: $url
        vendor_id: $vendor_id
    }) {
        ...basicManufacturerFields
    }
}


mutation InsertManufacturerWithVendor (
$name: String!
$url: String
$vendor: vendor_obj_rel_insert_input
) {
    manufacturer: insert_manufacturer_one(object: {
        name: $name
        url: $url
        vendor: $vendor
    }) {
        ...basicManufacturerFields
    }
}

mutation UpdateManufacturerUnchangedVendor (
$id: Int!
$name: String!
$url: String
) {
    manufacturer: update_manufacturer_by_pk(
        pk_columns: {
            id: $id, 
        }
        _set: {
            name: $name, 
            url: $url
        }
    ) {
        ...basicManufacturerFields
        ...objectManufacturerFields
    }
}


mutation DeleteManufacturer (
$id: Int!
) {
    delete_manufacturer_by_pk(id: $id) {
        ...basicManufacturerFields
    }
}


#############################################
## manufacturer specific vendor operations ##
#############################################

mutation InsertVendorWithExistingManufacturer (
$account_id: String
$name: String!
$url: String!
$manufacturer_id: Int!
) {
    insert_vendor_one(
        object: {
            account_id: $account_id
            name: $name
            url: $url
            manufacturer: {
                data: {
                    name: $name
                    url: $url
                    id: $manufacturer_id
                }, 
                on_conflict: {
                    constraint: manufacturer_pkey, 
                    update_columns: vendor_id
                }
            }
        }
    ) {
        id
        name
        url
        manufacturer {
            id
            name
            url
        }
    }
}


###########################
#### manufacturer_item ####
###########################


query GetManufacturerItems {
	manufacturer_item {
		...basicManufacturerItemFields
	}
}


query SearchManufacturerItems (
    $query_text: String!
    $item_id: Int
) {
    item: search_item(
        args: {
            query_text: $query_text
        }
        where: {
            manufacturerItems: {}
            id: {
                _eq: $item_id
            }
        }
    ) {
        id
        name: object(path: "name")
        object
        manufacturerItems {
            ...basicManufacturerItemFields
            manufacturer {
                id
                name
                url
            }
        }
    }
}

query GetManufacturerItem( $id: Int! ) {
    manufacturer_item: manufacturer_item_by_pk(id: $id) {
        ...basicManufacturerItemFields
		...objectManufacturerItemFields
    }
}

mutation UpdateManufacturerItem (
    $id: Int!
    $item_id: Int!
    $manufacturer_id: Int!
    $manufacturer_product_id: String!
    $manufacturer_product_name: String
    $manufacturer_product_series: String
    $product_url: String
    $description: String
) {
    manufacturer_item: update_manufacturer_item_by_pk(
    pk_columns: {
        id: $id, 
    }
    _set: {
        item_id: $item_id
        manufacturer_id: $manufacturer_id
        manufacturer_product_id: $manufacturer_product_id
        manufacturer_product_name: $manufacturer_product_name
        manufacturer_product_series: $manufacturer_product_series
        product_url: $product_url
        description: $description
    }
    ) {
        ...basicManufacturerItemFields
    }
}
mutation InsertManufacturerItem(
    # id
    $item_id: Int!
    $manufacturer_id: Int!
    $manufacturer_product_id: String!
    $manufacturer_product_name: String
    $manufacturer_product_series: String
    $product_url: String
    $description: String
) {
    manufacturer_item: insert_manufacturer_item_one(
    object: {
        item_id: $item_id
        manufacturer_id: $manufacturer_id
        manufacturer_product_id: $manufacturer_product_id
        manufacturer_product_name: $manufacturer_product_name
        manufacturer_product_series: $manufacturer_product_series
        product_url: $product_url
        description: $description
    }
    ) {
        ...basicManufacturerItemFields
    }
}

mutation DeleteManufacturerItem (
$id: Int!
) {
    manufacturer_item: delete_manufacturer_item_by_pk(id: $id) {
        ...basicManufacturerItemFields
    }
}
