query GetLabels {
  label(order_by: {created_at: asc}) {
    id
    created_at
    content
    is_template
    title
    item {
      id
      class
      name
    }
  }
}

query GetLabelById($label_id: uuid) {
  label(order_by: {created_at: asc}, where: {id: {_eq: $label_id}}) {
    id
    created_at
    content
    is_template
    title
    item {
      id
      class
      name
    }
  }
}

query GetLabelByItemId($item_id: Int) {
  label(order_by: {created_at: asc}, where: {item_id: {_eq: $item_id}}) {
    id
    created_at
    content
    is_template
    title
    item {
      id
      class
      name
    }
  }
}

query GetTemplates {
  label(order_by: {created_at: asc}, where: {is_template: {_eq: true}}) {
    id
    created_at
    content
    is_template
    title
    item {
      id
      class
      name
    }
  }
}
