fragment labelFields on label {
    id
    created_at
    content
    title
    width
    height
    item {
        id
        class
    }
}

query GetLabels {
    label(order_by: { created_at: asc }) {
        ...labelFields
    }
}

query GetLabel($label_id: uuid!) {
    label: label_by_pk(
        id: $label_id
    ) {
        ...labelFields
    }
}

query GetLabelByItemId($item_id: Int) {
    label (
        order_by: { created_at: asc }
        where: { item_id: { _eq: $item_id } }
    ) {
        ...labelFields
    }
}

query GetTemplates {
    label(
        order_by: { created_at: asc }, 
        where: { template_items: {} }
    ) {
        ...labelFields
    }
}

# Get non-template labels
query GetSingleLabels {
    label(
        order_by: { created_at: asc }, 
        where: { _not: { template_items: {} } }
        ) {
        id
    }
}
