mutation SaveLabel (
    $content: jsonb,
    $height: Int,
    $id: uuid,
    $item_id: Int,
    $title: String,
    $width: Int
) {
    insert_label(
      objects: {
            content: $content, 
            height: $height, 
            id: $id, 
            item_id: $item_id, 
            title: $title, 
            width: $width
        }
    ) {
        affected_rows
        returning {
            id
        }
  }
}

mutation EditLabel (
    $content: jsonb,
    $height: Int,
    $id: uuid,
    $item_id: Int,
    $title: String,
    $width: Int
){
  __typename
  update_label(
        where: {
            id: {
                _eq: $id
            }
        }, 
        _set: {
            content: $content, 
            height: $height, 
            item_id: $item_id, 
            title: $title, 
            width: $width
            # edit_of_id: "", 
        }
    ){
        returning {
            id
        }
        affected_rows
    }
}
