fragment ItemFields on item {
    id
    class
    name: object(path: "name")
    object
    # bundle {
    #     #
    # }
    # labels {
    #     #
    # }
    # manufacturerItems {
    #     #
    # }
    # orderItems {
    #     #
    # }
    # vendorItems {
    #     #
    # }
    # labelTemplates {
    #     #
    # }
}
# query SearchItems( $categories: [enum_item_class_enum!] ) {
#     items: item(
#         where: {
#             class: {
#                 _in: $categories
#             }
#         }
#         order_by: {id: asc}
#     ) {
#         ...ItemFields
#     }
# }

query GetItems($categories: [enum_item_class_enum!]) {
    items: item(where: { class: { _in: $categories } }, order_by: { id: asc }) {
        ...ItemFields
    }
}

query GetItem($id: Int!) {
    item: item_by_pk(id: $id) {
        ...ItemFields
    }
}

query ItemSearch($search_text: String!) {
    search(
        args: { 
            query_text: $search_text
        }, 
        # TODO: I need to come up with a way to specify _"Any `item_` class
        where: { 
            class: {} 
        }
    ) {
        id
        class
        name: text
    }
}

# query SearchItems {
#     item(
#         where: {
#             object: {
#                 # _has_key: "drive_size",
#                 _contains: { drive_size: "3" }
#             }
#         }
#     ) {
#         id
#         name: object(path: "name")
#         drive_size: object(path: "drive_size")
#     }
# }
