fragment ItemFields on item {
    id
    class
    name: object(path: "name")
    object
    # bundle {
    #     #
    # }
    # labels {
    #     #
    # }
    # manufacturerItems {
    #     #
    # }
    # orderItems {
    #     #
    # }
    # vendorItems {
    #     #
    # }
    # labelTemplates {
    #     #
    # }
}

query GetItems( $categories: [enum_item_class_enum!] ) {
    items: item( 
        where: {class: {_in: $categories}}
        order_by: {id: asc}
    ) {
        ...ItemFields
    }
}

query GetItem($id: Int!) {
    item(where: { id: { _eq: $id } }) {
        ...ItemFields
    }
}

# query SearchItems {
#     item(
#         where: {
#             object: {
#                 # _has_key: "drive_size",
#                 _contains: { drive_size: "3" }
#             }
#         }
#     ) {
#         id
#         name: object(path: "name")
#         drive_size: object(path: "drive_size")
#     }
# }
