fragment orderFields on order {
    vendor_order_id
    vendor {
        name
        url
    }
    url
    total_cost
    tax_cost
    pon
    placed_date
    payment_method_id
    items_cost
    id
    fulfilled_date
}

query GetOrdersByDateRange($date_start_gte: date, $date_end_lte: date) {
    order(
        where: { placed_date: { _gte: $date_start_gte, _lte: $date_end_lte } }
    ) {
        ...orderFields
    }
}

mutation InsertOrder(
    # $id: Int
    $fulfilled_date: date
    $items: order_item_arr_rel_insert_input
    $items_cost: money
    $payment_method: payment_method_obj_rel_insert_input
    $payment_method_id: Int
    $placed_date: date
    $pon: String
    $shipments: shipment_arr_rel_insert_input
    $tax_cost: money
    $total_cost: money
    $url: String
    $vendor: vendor_obj_rel_insert_input
    $vendor_id: Int
    $vendor_order_id: String
) {
    insert_order(
        objects: {
            items: $items # objects
            payment_method: $payment_method # objects
            shipments: $shipments # objects
            vendor: $vendor # object
            fulfilled_date: $fulfilled_date
            items_cost: $items_cost
            payment_method_id: $payment_method_id
            placed_date: $placed_date
            pon: $pon
            tax_cost: $tax_cost
            total_cost: $total_cost
            url: $url
            vendor_id: $vendor_id
            vendor_order_id: $vendor_order_id
        }
    ) {
        affected_rows
        returning {
            id
        }
    }
}

query GetOrders {
    order(order_by: { placed_date: asc }) {
        ...orderFields
    }
}

query GetOrder (
    $id: Int!
) {
  order: order_by_pk(id: $id) {
    vendor_order_id
    vendor_id
    url
    total_cost
    tax_cost
    pon
    placed_date
    payment_method_id
    items_cost
    id
    fulfilled_date
    items {
      cost_item
      cost_tax
      cost_total
      item_id
      manufacturer_item_id
      order_id
      quantity
      serial_no
      shipment_id
      vendor_item_id
    }
    items_aggregate {
      aggregate {
        count
      }
    }
    vendor {
      account_id
      id
      name
      url
    }
    shipments(distinct_on: id, limit: 10, offset: 10) {
      id
      order_id
      received_date
      shipped_date
      shipping_carrier
      tracking_id
      vendor_invoice_id
    }

    shipments_aggregate {
      aggregate {
        count
      }
    }

    
  }
}
