fragment basicOrderFields on order {
    id
    vendor_order_id
    url
    total_cost
    tax_cost
    pon
    placed_date
    payment_method_id
    items_cost
    fulfilled_date
}
fragment objectOrderFields on order {
    vendor {
        ...basicVendorFields
    }
}

query GetOrdersByDateRange($date_start_gte: date, $date_end_lte: date) {
    order(
        where: { placed_date: { _gte: $date_start_gte, _lte: $date_end_lte } }
    ) {
        ...basicOrderFields
        ...objectOrderFields
    }
}

query GetOrders {
    order(order_by: { placed_date: desc }) {
        ...basicOrderFields
        ...objectOrderFields
    }
}

query GetOrder($id: Int!) {
    order: order_by_pk(id: $id) {
        vendor_order_id
        vendor_id
        url
        total_cost
        tax_cost
        pon
        placed_date
        payment_method_id
        items_cost
        id
        fulfilled_date
        order_items {
            cost_item
            cost_tax
            cost_total
            item_id
            manufacturer_item_id
            order_id
            quantity
            serial_no
            shipment_id
            vendor_item_id
        }
        order_items_aggregate {
            aggregate {
                count
            }
        }
        vendor {
            id
            account_id
            name
            url
        }
        shipments(distinct_on: id, limit: 10, offset: 10) {
            id
            order_id
            received_date
            shipped_date
            shipping_carrier
            tracking_id
            vendor_invoice_id
        }

        shipments_aggregate {
            aggregate {
                count
            }
        }
    }
}

mutation InsertOrder(
    # $id: Int
    $fulfilled_date: date
    $order_items: [order_item_insert_input!]!
    $items_cost: numeric
    $payment_method: payment_method_obj_rel_insert_input
    $payment_method_id: Int
    $placed_date: date
    $pon: String
    $shipments: shipment_arr_rel_insert_input
    $tax_cost: numeric
    $total_cost: numeric
    $url: String
    $vendor: vendor_obj_rel_insert_input
    $vendor_id: Int
    $vendor_order_id: String
) {
    order: insert_order_one (
        object: {
            order_items: { data: $order_items } # objects
            payment_method: $payment_method # objects
            shipments: $shipments # objects
            vendor: $vendor # object
            fulfilled_date: $fulfilled_date
            items_cost: $items_cost
            payment_method_id: $payment_method_id
            placed_date: $placed_date
            pon: $pon
            tax_cost: $tax_cost
            total_cost: $total_cost
            url: $url
            vendor_id: $vendor_id
            vendor_order_id: $vendor_order_id
        }
    ) {
        ...basicOrderFields
        ...objectOrderFields
    }
}

mutation UpdateOrder (
    $id: Int!
    $fulfilled_date: date
    $items_cost: numeric
    $payment_method_id: Int
    $placed_date: date
    $pon: String
    $tax_cost: numeric
    $total_cost: numeric
    $url: String
    $vendor_id: Int
    $vendor_order_id: String
) {
    order: update_order_by_pk(
    pk_columns: {
        id: $id, 
    }
    _set: {
        fulfilled_date: $fulfilled_date
        items_cost: $items_cost
        payment_method_id: $payment_method_id
        placed_date: $placed_date
        pon: $pon
        tax_cost: $tax_cost
        total_cost: $total_cost
        url: $url
        vendor_id: $vendor_id
        vendor_order_id: $vendor_order_id
    }
    ) {
        ...basicOrderFields
        ...objectOrderFields
    }
}

