# escape=`

FROM stefanscherer/node-windows:10.16.3-windowsservercore-2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /tmp
COPY package.json /tmp/
RUN npm config set registry http://registry.npmjs.org/ ; `
    npm install

WORKDIR /app
RUN Copy-Item -Recurse /tmp/node_modules /app/
COPY package.json /app/
COPY tsconfig.json /app/
COPY src /app/src

CMD npm run-script run
EXPOSE 8080
