fragment ItemHardwareFastenerScrewMachineFields on item_hardware_fastener_screw_machine {
    id
    name
    description
    unit
    thread_length
    head_type
    drive_type
    drive_size
    head_diameter
    head_height
    thread_diameter_label
    finish
    material
    thread_direction
    countersunk_angle
    tensile_strength
    specifications_met
    thread_fit
    point_type
    hardness
    strength_class
    use_material
    diameter {
        ...ItemHardwareFastenerScrewMachineDiameterFields
    }
}

fragment ItemHardwareFastenerScrewMachineDiameterFields on property_item_hardware_fastener_screw_machine_diameter {
    diameter_label
    diameter_major
    fit
    pitch
    pitch_label
    standard
    thread_label
    unit
}

query item_hardware_fastener_screw_machine {
    items: item_hardware_fastener_screw_machine(order_by: { id: asc }) {
        ...ItemHardwareFastenerScrewMachineFields
    }
}

mutation InsertItemHardwareFastenerScrewMachine (
    $countersunk_angle: numeric
    $countersunk_height: numeric
    $description: String
    $drive_size: String
    $default_fields: jsonb
    $drive_type: enum_item_hardware_fastener_drive_enum
    $embedded_length: numeric
    $finish: enum_item_hardware_finish_enum
    $hardness: enum_item_hardware_fastener_screw_hardness_enum
    $head_diameter: numeric
    $head_height: numeric
    $head_type: enum_item_hardware_fastener_screw_head_enum
    # $id: Int
    $material: enum_item_hardware_fastener_material_enum
    $name: String
    $point_type: enum_item_hardware_fastener_screw_machine_point_enum
    $specifications_met: jsonb
    $strength_class: enum_item_hardware_fastener_screw_machine_strength_enum
    $tensile_strength: numeric
    $thread_diameter_label: String
    $thread_direction: enum_item_handedness_enum
    $thread_fit: enum_item_hardware_fastener_screw_machine_thread_fit_enum
    $thread_length: numeric
    # $thread_label: enum_item_hardware_fastener_thread_label_enum
    $thread_pitch: numeric
    $thread_standard: enum_item_hardware_fastener_thread_standard_enum
    $unit: enum_unit_enum
    $use_material: enum_item_hardware_use_material_enum
) {
    insert_item_hardware_fastener_screw_machine_one(
        object: {
            countersunk_angle: $countersunk_angle
            countersunk_height: $countersunk_height
            description: $description
            drive_size: $drive_size
            default_fields: $default_fields
            drive_type: $drive_type
            embedded_length: $embedded_length
            finish: $finish
            hardness: $hardness
            head_diameter: $head_diameter
            head_height: $head_height
            head_type: $head_type
            material: $material
            name: $name
            point_type: $point_type
            specifications_met: $specifications_met
            strength_class: $strength_class
            tensile_strength: $tensile_strength
            thread_diameter_label: $thread_diameter_label
            thread_direction: $thread_direction
            thread_fit: $thread_fit
            # thread_label: $thread_label
            # diameter {
            #     # diameter_label
            #     # diameter_major
            #         # fit
            #     # pitch
            #     # pitch_label
            #     # standard
            #     thread_label: $thread_label
            #     # unit
            # }
            thread_length: $thread_length
            thread_pitch: $thread_pitch
            thread_standard: $thread_standard
            unit: $unit
            use_material: $use_material
        }
    ) {
        ...ItemHardwareFastenerScrewMachineFields
    }
}
query GetEnumItemHardwareFastenerThreadStandard {
    enum_item_hardware_fastener_thread_standard {
        id
        description
    }
}

mutation UpdateItemHardwareFastenerScrewMachine(
    $countersunk_angle: numeric
    $countersunk_height: numeric
    $description: String
    $drive_size: String
    $default_fields: jsonb
    $drive_type: enum_item_hardware_fastener_drive_enum
    $embedded_length: numeric
    $finish: enum_item_hardware_finish_enum
    $hardness: enum_item_hardware_fastener_screw_hardness_enum
    $head_diameter: numeric
    $head_height: numeric
    $head_type: enum_item_hardware_fastener_screw_head_enum
    $id: Int!
    $material: enum_item_hardware_fastener_material_enum
    $name: String
    $point_type: enum_item_hardware_fastener_screw_machine_point_enum
    $specifications_met: jsonb
    $strength_class: enum_item_hardware_fastener_screw_machine_strength_enum
    $tensile_strength: numeric
    $thread_diameter_label: String
    $thread_direction: enum_item_handedness_enum
    $thread_fit: enum_item_hardware_fastener_screw_machine_thread_fit_enum
    $thread_length: numeric
    # $thread_label: enum_item_hardware_fastener_thread_label_enum
    $thread_pitch: numeric
    $thread_standard: enum_item_hardware_fastener_thread_standard_enum
    $unit: enum_unit_enum
    $use_material: enum_item_hardware_use_material_enum
) {
    update_item_hardware_fastener_screw_machine_by_pk(
        pk_columns: { id: $id }
        _set: {
            use_material: $use_material
            unit: $unit
            thread_standard: $thread_standard
            thread_pitch: $thread_pitch
            thread_length: $thread_length
            # thread_label: $thread_label
            thread_fit: $thread_fit
            thread_direction: $thread_direction
            thread_diameter_label: $thread_diameter_label
            tensile_strength: $tensile_strength
            strength_class: $strength_class
            specifications_met: $specifications_met
            point_type: $point_type
            name: $name
            material: $material
            head_type: $head_type
            head_height: $head_height
            head_diameter: $head_diameter
            hardness: $hardness
            finish: $finish
            embedded_length: $embedded_length
            drive_type: $drive_type
            description: $description
            drive_size: $drive_size
            default_fields: $default_fields
            countersunk_height: $countersunk_height
            countersunk_angle: $countersunk_angle
        }
    ) {
        ...ItemHardwareFastenerScrewMachineFields
    }
}
