

mutation InsertIcon (
    $mimeData: String, 
    $description: String, 
    $id: uuid, 
    $title: String,
    $categories: icon_item_category_map_arr_rel_insert_input
    $labels: icon_label_map_arr_rel_insert_input
    ) {
  insert_icon(
      objects: {
          data: $mimeData, 
          description: $description, 
          id: $id, 
          title: $title, 
          categories: $categories,
          labels: $labels
        }
    ){
        affected_rows 
  }
}

# mutation UploadImageFile (
#   $files: [ Upload! ]!
# ) {
#   uploadFiles(files: $files) {
#     name
#     path
#     type
#     base64
#   }
# }


query GetIcon($id: uuid!) {
  icon: icon_by_pk(id: $id) {
    data
    description
    id
    title
    categories {
        category
        criteria
        sequence
    }
    labels {
        label_id
    }
  }
}
query GetIcons {
  icon {
    data
    description
    id
    title
    categories {
        category
        criteria
        sequence
    }
    labels {
        label_id
    }
  }
}