

query GetPrinterStatus {
  PrinterStatus {
    labelType
    heightInch
    labelStatus {
      labelCharacteristic {
        pinsRight
        pinsPrint
        pinsLeft
        widthMillimeters
      }
    }
  }
}