mutation SendBuffer($buffer: [[[uint8]]]!) {
    putLabelMonochromeBuffer(imageBuffer: $buffer) {
        imageBuffer
    }
}
# mutation SendBuffer ($buffer: [[[Int]]]) {
#   putLabelMonochromeBuffer(imageBuffer: $buffer)
# }

# [[[256,0,256,0,256],[0,256,0,256,0]]]


query GetPrinterStatus {
  PrinterStatus {
    labelType
    labelStatus {
      labelCharacteristic {
        pinsRight
        pinsPrint
        pinsLeft
        widthMillimeters
      }
    }
  }
}